// Pure helpers for the Worker, kept free of Cloudflare APIs so they can be unit-tested.

export const MAX_IMAGE_B64 = 6_000_000; // ~4.5 MB PNG; the extension caps images at 1400 px

export function bearer(request) {
  const h = request.headers.get("Authorization") || "";
  const m = /^Bearer\s+(\S+)$/i.exec(h);
  return m ? m[1] : null;
}

export function todayKey(now = new Date()) {
  return now.toISOString().slice(0, 10);
}

// Invite tokens look like cc_<22 url-safe chars>; generated by scripts/invite.sh.
export function isTokenShaped(token) {
  return typeof token === "string" && /^cc_[A-Za-z0-9_-]{16,64}$/.test(token);
}

// Only the fields the model prompt uses; nothing else from the client is forwarded.
export function sanitizeContext(ctx) {
  const c = ctx && typeof ctx === "object" ? ctx : {};
  const str = (v, max) => (typeof v === "string" ? v.slice(0, max) : "");
  return {
    now: str(c.now, 40),
    weekday: str(c.weekday, 12),
    timezone: str(c.timezone, 64) || "UTC",
    pageTitle: str(c.pageTitle, 200),
    pageUrl: str(c.pageUrl, 500)
  };
}

export function validateBody(body) {
  if (!body || typeof body !== "object") return "bad json";
  if (typeof body.image !== "string" || !body.image) return "missing image";
  if (typeof body.screen !== "string" || !body.screen) return "missing screen image";
  if (body.image.length > MAX_IMAGE_B64 || body.screen.length > MAX_IMAGE_B64) return "image too large";
  return null;
}

// ---- Quota logic (pure). The QuotaCounter Durable Object runs these between a
// synchronous storage read and write, so one invite code's check-and-increment
// can never interleave with another request for the same code — unlike a KV
// read-then-write, which a parallel burst outruns.

export const BURST_WINDOW_MS = 60_000;
export const GLOBAL_NAME = "global"; // real codes start with "cc_", so no collision

// state = { day, used, recent: [ms timestamps of reservations in the window] }.
// burst = max reservations per BURST_WINDOW_MS (0 disables the burst check).
export function reserveIn(state, { day, limit, burst = 0, now }) {
  const prev = state || {};
  const used = prev.day === day ? prev.used || 0 : 0;
  const recent = burst > 0 ? (prev.recent || []).filter((t) => now - t < BURST_WINDOW_MS) : [];
  if (burst > 0 && recent.length >= burst) {
    return { ok: false, reason: "burst", used, state: { day, used, recent } };
  }
  if (used >= limit) return { ok: false, reason: "daily", used, state: { day, used, recent } };
  if (burst > 0) recent.push(now);
  return { ok: true, used: used + 1, state: { day, used: used + 1, recent } };
}

// Refund for a reservation whose model call failed. The burst timestamp stays:
// retries against a failing upstream still count toward the per-minute limit.
export function releaseIn(state, day) {
  if (!state || state.day !== day || !(state.used > 0)) return state || null;
  return { ...state, used: state.used - 1 };
}

export function usedIn(state, day) {
  return state && state.day === day ? state.used || 0 : 0;
}

export const MAX_REQUEST_BYTES = 13_000_000; // two ≤6 MB base64 images + context, with slack

// Rejects oversized uploads from the Content-Length header before the body is
// read or parsed.
export function requestTooLarge(request) {
  return Number(request.headers.get("Content-Length") || 0) > MAX_REQUEST_BYTES;
}

// CORS headers are issued only to browser-extension origins. A web page that
// somehow holds an invite code gets no Access-Control-Allow-Origin, so the
// browser blocks it; curl/scripts are unaffected (CORS is a browser concept).
const EXTENSION_ORIGIN = /^(chrome|moz|safari-web)-extension:\/\/[a-z0-9-]+$/i;
export function corsHeaders(origin) {
  if (!origin || !EXTENSION_ORIGIN.test(origin)) return {};
  return {
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Headers": "Content-Type, Authorization",
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    Vary: "Origin"
  };
}

// Wrapper over Cloudflare's rate-limiting binding (per IP, before any lookup).
// Measured weak in production (approximate, per location), so it only trims
// noise; the Durable Object is the real limit. Allows when absent or erroring.
export async function rateLimitOk(limiter, key) {
  if (!limiter || !key) return true;
  try {
    return (await limiter.limit({ key })).success !== false;
  } catch {
    return true;
  }
}

export function geminiErrorMessage(status, detail) {
  const msg = detail?.error?.message || "";
  if (status === 429) return { status: 503, error: "The hosted model is rate-limited right now — try again in a minute" };
  if (status === 503) return { status: 503, error: "The hosted model is busy right now — try again in a minute" };
  if (status === 400 && /API key/i.test(msg)) return { status: 500, error: "Proxy misconfigured (Gemini key)" };
  return { status: 502, error: `Model error ${status}${msg ? `: ${msg.slice(0, 160)}` : ""}` };
}
