// Pure helpers for the Worker, kept free of Cloudflare APIs so they can be unit-tested.

export const MAX_IMAGE_B64 = 6_000_000; // ~4.5 MB PNG; the extension caps images at 1400 px

export function bearer(request) {
  const h = request.headers.get("Authorization") || "";
  const m = /^Bearer\s+(\S+)$/i.exec(h);
  return m ? m[1] : null;
}

export function todayKey(now = new Date()) {
  return now.toISOString().slice(0, 10);
}

// Invite tokens look like cc_<22 url-safe chars>; generated by scripts/invite.sh.
export function isTokenShaped(token) {
  return typeof token === "string" && /^cc_[A-Za-z0-9_-]{16,64}$/.test(token);
}

// Only the fields the model prompt uses; nothing else from the client is forwarded.
export function sanitizeContext(ctx) {
  const c = ctx && typeof ctx === "object" ? ctx : {};
  const str = (v, max) => (typeof v === "string" ? v.slice(0, max) : "");
  return {
    now: str(c.now, 40),
    weekday: str(c.weekday, 12),
    timezone: str(c.timezone, 64) || "UTC",
    pageTitle: str(c.pageTitle, 200),
    pageUrl: str(c.pageUrl, 500)
  };
}

export function validateBody(body) {
  if (!body || typeof body !== "object") return "bad json";
  if (typeof body.image !== "string" || !body.image) return "missing image";
  if (typeof body.screen !== "string" || !body.screen) return "missing screen image";
  if (body.image.length > MAX_IMAGE_B64 || body.screen.length > MAX_IMAGE_B64) return "image too large";
  return null;
}

// KV is eventually consistent, so this is a soft limit — fine for invite-only testing.
export async function readQuota(kv, token, limit, now = new Date()) {
  const key = `use:${token}:${todayKey(now)}`;
  const used = Number((await kv.get(key)) || 0);
  return { key, used, limit, allowed: used < limit };
}

// KV allows ~1 write/s per key; under a burst the increment can be refused.
// Losing a count is preferable to failing a crop the user already paid for in
// latency, so the limit stays soft.
export async function bumpQuota(kv, key, used) {
  try {
    await kv.put(key, String(used + 1), { expirationTtl: 2 * 24 * 3600 });
  } catch {
    // soft limit
  }
}

// The service-wide daily counter shares the per-code key scheme; real codes
// always start with "cc_", so "global" can never collide with one.
export const GLOBAL_TOKEN = "global";

export const MAX_REQUEST_BYTES = 13_000_000; // two ≤6 MB base64 images + context, with slack

// Rejects oversized uploads from the Content-Length header before the body is
// read or parsed.
export function requestTooLarge(request) {
  return Number(request.headers.get("Content-Length") || 0) > MAX_REQUEST_BYTES;
}

// CORS headers are issued only to browser-extension origins. A web page that
// somehow holds an invite code gets no Access-Control-Allow-Origin, so the
// browser blocks it; curl/scripts are unaffected (CORS is a browser concept).
const EXTENSION_ORIGIN = /^(chrome|moz|safari-web)-extension:\/\/[a-z0-9-]+$/i;
export function corsHeaders(origin) {
  if (!origin || !EXTENSION_ORIGIN.test(origin)) return {};
  return {
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Headers": "Content-Type, Authorization",
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    Vary: "Origin"
  };
}

// Wrapper over Cloudflare's rate-limiting binding. Allows when the binding is
// absent (older local dev) or errors — the invite code and daily quotas still
// gate the request; this only shaves bursts.
export async function rateLimitOk(limiter, key) {
  if (!limiter || !key) return true;
  try {
    return (await limiter.limit({ key })).success !== false;
  } catch {
    return true;
  }
}

export function geminiErrorMessage(status, detail) {
  const msg = detail?.error?.message || "";
  if (status === 429) return { status: 503, error: "The hosted model is rate-limited right now — try again in a minute" };
  if (status === 503) return { status: 503, error: "The hosted model is busy right now — try again in a minute" };
  if (status === 400 && /API key/i.test(msg)) return { status: 500, error: "Proxy misconfigured (Gemini key)" };
  return { status: 502, error: `Model error ${status}${msg ? `: ${msg.slice(0, 160)}` : ""}` };
}
